config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }


  root to:'ideas#index',  as: 'posts_with_button'

  get  "/page", to: 'pages#index'

  resources :ideas, only: [:index, :show, :create, :destroy, :new] do
    member do
      put "like", to: "ideas#upvote"
      put "dislike", to: "ideas#downvote"
    end
  end

  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, :description, presence: true
  acts_as_votable
  self.per_page = 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 acts_as_voter
 has_many :votes
 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
 validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
 attr_accessor :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:first_name, :last_name, :avatar, :email, :password)
    end

    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:first_name, :last_name, :email, :password, :current_password, :avatar)
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(user_id: params[:user_id], idea_id: params[:idea_id], comment: params[:comment])
    redirect_to '/'
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
require 'will_paginate/array'

  def index
    if current_user
      @user = current_user.id
    else
      @user = "n/a"
    end
    @ideas = Idea.all.sort_by { |idea| idea.get_downvotes.size - idea.get_upvotes.size}.paginate(page: params[:page], per_page: 5)
      respond_to do |format|
        format.html
        format.js {render 'paginate'}
    end
    # @ideas = @ideas.sort_by { |idea| idea.get_downvotes.size - idea.get_upvotes.size}
  end

  def show
    @idea = Idea.find_by(id: params[:id])
  end

  def new
  end

  def create
    idea = Idea.new(title: params[:title], description: params[:description], user_id: params[:user_id])
    if current_user
      idea.save
      redirect_to ''
    else
      redirect_to new_user_registration_path
    end
  end

  def upvote
    @idea = Idea.find(params[:id])
    @idea.upvote_by current_user
    redirect_to '/'
  end

  def downvote
    @idea = Idea.find(params[:id])
    @idea.downvote_by current_user
    redirect_to '/'
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  prepend_before_action :set_minimum_password_length
  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]


  def new
    super
  end


  def create
    super
  end


  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def net_score(idea)
    idea.get_upvotes.size - idea.get_downvotes.size
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_idea.html.haml
.wrapper
  .idea-response
    .vote
      = link_to like_idea_path(idea), method: :put do
        %span{:class => "fa fa-arrow-up icon-4x"}
        %div
          \#{idea.get_upvotes.size}
    .score
      =net_score(idea)
    .vote
      = link_to dislike_idea_path(idea), method: :put do
        %div
          \#{idea.get_downvotes.size}
        %span{:class => "fa fa-arrow-down icon-4x"}
  .idea-content
    #idea-name
      =link_to "/ideas/#{idea.id}" do
        #{idea.title}
    #idea-descript= idea.description
    .actions-wrapper
      %a.btn.btn-primary{"onclick" => "myFunction('collapse#{idea.id}')", "aria-controls" => "collapse#{idea.id}", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapse#{idea.id}"}   comments #{idea.comments.size}
      #idea-owner
        -# #{idea.user.first_name} #{idea.user.last_name}
        #{idea.created_at.strftime("%I:%M %P %b %d")}
    %div{ :id => "collapse#{idea.id}", :class => "collapse" }
      .comments-wrapper
        -idea.comments.each do |comment|
          .comment
            #comment-user
              -# .img-circle-comment= user_photo(:navbar, comment.user.profiles.first)
              #{comment.user.first_name} #{comment.user.last_name}
            #comment-body
              #{comment.comment}
      = form_tag "/comments", method: :post do
        .social= social_share_button_tag("Can you solve this problem?")
        %input{:name => "idea_id", :type => "hidden", :value => "#{idea.id}"}/
        - if  user_signed_in?
          .comment-input
            %input{:name => "user_id", :type => "hidden", :value => "#{current_user.id}"}/
            %textarea{ :placeholder => "Comment Here", :cols => "70", :name => "comment", :rows => "1"}
            :preserve
            %button#submit{:type => "submit"} Submit

app/views/ideas/index.html.haml
.ideas-page
  .new-idea
    = form_tag "/ideas", method: :post do
      %input{:name => "user_id", :type => "hidden", :value => @user }/
      %textarea{:cols => "120", :name => "title", :rows => "1", :placeholder => "Name your idea and bring it to life!"}
      %textarea{:cols => "120", :name => "description", :rows => "1", :placeholder => "Tell us about your idea"}
      %input.submit{:name => "Post", :type => "submit", :value => "New Idea"}/

  -@ideas.each do |idea|
    =render 'idea', idea: idea
  =will_paginate @ideas

app/views/ideas/index.js.erb
$('#ideas').append('<%= escape_javascript render(@ideas) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@ideas) %>');

app/views/ideas/show.html.haml
.ideas-page
  =render 'idea', idea: @idea

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<!--
  Retrospect by TEMPLATED
  templated.co @templatedco
  Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
  <head>
    <title>Think About It</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="assets/css/main.css" />
    <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
  </head>
  <body class="landing">

    <!-- Header -->
      <header id="header" class="alt">
        <h1><a href="index.html">Retrospect</a></h1>
        <a href="#nav">Menu</a>
      </header>

    <!-- Nav -->
      <nav id="nav">
        <ul class="links">
          <li><a href="/">Home</a></li>
          <li><%= link_to('Edit registration', edit_user_registration_path) %></li>
            <% if user_signed_in? %>
            <li><%= link_to('Edit Profile', edit_user_registration_path) %></li>
              <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
            <% else %>
              <li><%= link_to('Sign Up', new_user_registration_path) %></li>
            <% end %>
        </ul>
      </nav>

    <!-- Banner -->
      <section id="banner">
        <i class="icon fa-anchor"></i>
        <h2>Think Tenk</h2>
        <p>All Fish Welcome</p>
        <ul class="actions">
        </ul>
      </section>
      <% flash.each do |name, message| %>
      <div class="alert alert-<%= name %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= message %>
      <% end %>
      </div>
<%= yield %>
    <!-- Footer -->
      <footer id="footer">
        <div class="inner">
          <ul class="icons">
            <li><a href="#" class="icon fa-facebook">
              <span class="label">Facebook</span>
            </a></li>
            <li><a href="#" class="icon fa-twitter">
              <span class="label">Twitter</span>
            </a></li>
            <li><a href="#" class="icon fa-instagram">
              <span class="label">Instagram</span>
            </a></li>
            <li><a href="#" class="icon fa-linkedin">
              <span class="label">LinkedIn</span>
            </a></li>
          </ul>
          <ul class="copyright">
            <li>&copy; Untitled.</li>
            <li>Images: <a href="http://unsplash.com">Unsplash</a>.</li>
            <li>Design: <a href="http://templated.co">TEMPLATED</a>.</li>
          </ul>
        </div>
      </footer>

    <!-- Scripts -->
      <script src="assets/js/jquery.min.js"></script>
      <script src="assets/js/skel.min.js"></script>
      <script src="assets/js/util.js"></script>
      <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
      <script src="assets/js/main.js"></script>

  </body>
</html>

app/views/pages/index.html.erb
<h1>Hello World</h1>

<% if user_signed_in? %>
  <%= link_to "sign out", destroy_user_session_path %>
<% else %>
  <%= link_to "sign up", new_user_registration_path%>
  <%= link_to "sign in", new_user_session_path%>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>